services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: localdevpassword
      MYSQL_DATABASE: w9demo
    volumes:
      - dbdata:/var/lib/mysql

  app:
    image: mysql:8.0
    command: sleep 3600
    depends_on:
      - db

volumes:
  dbdata:
